<a href="https://colab.research.google.com/github/Shashi-kumar-g/machine-learning-26/blob/main/employee%20salary.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import files

uploaded = files.upload()

Saving employee_income.csv to employee_income (1).csv

In [3]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [4]:
df = pd.read_csv("employee_income.csv")

print("First 5 rows:")
display(df.head())

print("\nDataset Shape:")
print(df.shape)

print("\nColumn Names:")
print(df.columns.tolist())

First 5 rows:

   age  experience  income
0   50           5   45118
1   36           9   41691
2   29           3   35994
3   42           5   41614
4   40          12   51474

Dataset Shape:
(50, 3)

Column Names:
['age', 'experience', 'income']

In [5]:
if "id" in df.columns:
    df = df.drop(columns=["id"])

print(df.head())

   age  experience  income
0   50           5   45118
1   36           9   41691
2   29           3   35994
3   42           5   41614
4   40          12   51474

In [6]:
# Independent variables
X = df[["age", "experience"]]

# Dependent variable
y = df["income"]

print("Input variables:")
display(X.head())

print("Target variable:")
display(y.head())

Input variables:

   age  experience
0   50           5
1   36           9
2   29           3
3   42           5
4   40          12

Target variable:

0    45118
1    41691
2    35994
3    41614
4    51474
Name: income, dtype: int64

In [7]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

Training samples: 40
Testing samples: 10

In [8]:
model = LinearRegression()

model.fit(X_train, y_train)

print("Model training completed!")

Model training completed!

In [9]:
y_pred = model.predict(X_test)

print("Predicted values:")
print(y_pred)

Predicted values:
[46541.08535234 32318.05975196 44824.55463946 48154.61123684
 46541.08535234 48065.54352798 52106.32679899 32599.19999806
 48465.44071923 53127.882955  ]

In [10]:
mae = mean_absolute_error(y_test, y_pred)

rmse = np.sqrt(mean_squared_error(y_test, y_pred))

r2 = r2_score(y_test, y_pred)

print("Model Evaluation")
print("-----------------------")
print("MAE  :", mae)
print("RMSE :", rmse)
print("R²   :", r2)

Model Evaluation
-----------------------
MAE  : 1581.4121026423527
RMSE : 1749.6763847604439
R²   : 0.9349274275513149

In [11]:
print("Intercept:", model.intercept_)
print("Age coefficient:", model.coef_[0])
print("Experience coefficient:", model.coef_[1])

Intercept: 19574.050974164893
Age coefficient: 310.8294823851975
Experience coefficient: 1524.4581756399275

In [12]:
print(
    f"\nIncome = {model.intercept_:.2f} "
    f"+ ({model.coef_[0]:.2f} × Age) "
    f"+ ({model.coef_[1]:.2f} × Experience)"
)

Income = 19574.05 + (310.83 × Age) + (1524.46 × Experience)

In [13]:
results = pd.DataFrame({
    "Actual Income": y_test.values,
    "Predicted Income": y_pred
})

display(results)

   Actual Income  Predicted Income
0          47998      46541.085352
1          33491      32318.059752
2          46088      44824.554639
3          50179      48154.611237
4          44204      46541.085352
5          48057      48065.543528
6          49828      52106.326799
7          33440      32599.199998
8          50334      48465.440719
9          55691      53127.882955