<a href="https://colab.research.google.com/github/Shashi-kumar-g/machine-learning-26/blob/main/ml_task_day2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files

uploaded = files.upload()

Saving loan_default_day2 - loan_default_day2.csv to loan_default_day2 - loan_default_day2 (1).csv

In [3]:
import pandas as pd
import numpy as np

# Using the actual uploaded file name
df = pd.read_csv("loan_default_day2 - loan_default_day2.csv")

print("Dataset loaded successfully!")
print("Shape:", df.shape)

Dataset loaded successfully!
Shape: (5350, 16)

In [4]:
df.head()

,loan_id,applicant_name,age,employment_type,employment_years,monthly_income,loan_amount,loan_date,credit_score,region,collection_calls,recovery_amount,account_closed_date,risk_flag,late_but_repaid,defaulted_12m
0,10136,Sanjay Patel,46,Salaried,20,39500.0,283000,2022-08-27,676,Saurashtra,0,0,2023-04-27,low,N,0
1,10825,Kinjal Solanki,47,SE,22,25200.0,457000,2022-05-07,567,Saurashtra,2,0,2023-01-09,low,N,0
2,11557,Priya Zala,52,Daily wage,31,9800.0,52000,2022-04-22,684,North Gujarat,0,0,NaN,low,N,1
3,10867,Kiran Vora,46,self employed,18,NaN,340000,2022-10-09,707,Saurashtra,0,0,NaN,low,N,0
4,10431,Dhruv Dave,27,Salaried,2,NaN,442000,2023-05-23,728,Saurashtra,0,0,NaN,high,Y,1

In [7]:
print("Columns in the dataset:")
print(df.columns.tolist())

Columns in the dataset:
['loan_id', 'applicant_name', 'age', 'employment_type', 'employment_years', 'monthly_income', 'loan_amount', 'loan_date', 'credit_score', 'region', 'collection_calls', 'recovery_amount', 'account_closed_date', 'risk_flag', 'late_but_repaid', 'defaulted_12m']

In [6]:
df.dtypes

loan_id                  int64
applicant_name          object
age                      int64
employment_type         object
employment_years         int64
monthly_income         float64
loan_amount              int64
loan_date               object
credit_score             int64
region                  object
collection_calls         int64
recovery_amount          int64
account_closed_date     object
risk_flag               object
late_but_repaid         object
defaulted_12m            int64
dtype: object

In [8]:
df.describe()

,loan_id,age,employment_years,monthly_income,loan_amount,credit_score,collection_calls,recovery_amount,defaulted_12m
count,5350.000000,5350.000000,5350.000000,4.595000e+03,5.350000e+03,5350.000000,5350.000000,5350.000000,5350.000000
mean,12569.532150,37.944112,76.188785,3.986177e+04,4.341793e+05,681.059626,1.291963,24892.635514,0.219252
std,1487.996407,9.801472,240.216829,1.482944e+05,2.869913e+05,70.481009,2.711323,75527.705883,0.413779
min,10001.000000,0.000000,0.000000,0.000000e+00,2.400000e+04,436.000000,0.000000,0.000000,0.000000
25%,11280.250000,31.000000,7.000000,2.400000e+04,2.250000e+05,633.000000,0.000000,0.000000,0.000000
50%,12569.500000,38.000000,14.000000,3.520000e+04,3.665000e+05,681.000000,0.000000,0.000000,0.000000
75%,13860.750000,45.000000,22.000000,4.870000e+04,5.827500e+05,727.000000,1.000000,0.000000,0.000000
max,15150.000000,65.000000,999.000000,9.999999e+06,2.481000e+06,900.000000,17.000000,970100.000000,1.000000

In [9]:
text_columns = df.select_dtypes(include="object").columns

for col in text_columns:
    print("\n==============================")
    print("Column:", col)
    print("==============================")
    print(df[col].value_counts(dropna=False))

==============================
Column: applicant_name
==============================
applicant_name
Vijay Gohil      27
Pooja Bhatt      27
Sanjay Bhatt     27
Rekha Gohil      27
Nirav Rathod     27
                 ..
anita dave        1
dhruv dave        1
SANJAY JADEJA     1
VIJAY CHAUHAN     1
RAVI SOLANKI      1
Name: count, Length: 432, dtype: int64

==============================
Column: employment_type
==============================
employment_type
Salaried         2117
Business         1073
Daily wage        838
Self-employed     836
Self employed     140
Self-Employed     124
SE                117
self employed     105
Name: count, dtype: int64

==============================
Column: loan_date
==============================
loan_date
2021-09-24    14
2022-07-21    14
2022-07-23    14
2021-11-03    13
2021-09-28    13
              ..
2022-12-01     1
2021-11-08     1
2022-05-02     1
2022-10-25     1
2021-12-06     1
Name: count, Length: 898, dtype: int64

==============================
Column: region
==============================
region
Saurashtra         1637
North Gujarat      1069
Central Gujarat    1037
Kutch               820
South Gujarat       787
Name: count, dtype: int64

==============================
Column: account_closed_date
==============================
account_closed_date
NaN           4413
2023-09-12       6
2023-06-13       6
2022-03-29       6
2022-10-10       6
              ...
2023-04-04       1
2022-05-28       1
2024-03-01       1
2022-01-06       1
2022-07-21       1
Name: count, Length: 571, dtype: int64

==============================
Column: risk_flag
==============================
risk_flag
low     4181
high    1169
Name: count, dtype: int64

==============================
Column: late_but_repaid
==============================
late_but_repaid
N    5016
Y     334
Name: count, dtype: int64

In [10]:
missing = df.isnull().sum()

print("Missing values:")
print(missing)

Missing values:
loan_id                   0
applicant_name            0
age                       0
employment_type           0
employment_years          0
monthly_income          755
loan_amount               0
loan_date                 0
credit_score              0
region                    0
collection_calls          0
recovery_amount           0
account_closed_date    4413
risk_flag                 0
late_but_repaid           0
defaulted_12m             0
dtype: int64

In [12]:
missing_percent = (df.isnull().sum() / len(df)) * 100

print("Missing percentage:")
print(missing_percent.sort_values(ascending=False))

Missing percentage:
account_closed_date    82.485981
monthly_income         14.112150
age                     0.000000
loan_id                 0.000000
employment_type         0.000000
employment_years        0.000000
loan_amount             0.000000
applicant_name          0.000000
loan_date               0.000000
credit_score            0.000000
collection_calls        0.000000
region                  0.000000
recovery_amount         0.000000
risk_flag               0.000000
late_but_repaid         0.000000
defaulted_12m           0.000000
dtype: float64

In [13]:
print("Age = 0:")
print((df["age"] == 0).sum())

print("\nEmployment years = 999:")
print((df["employment_years"] == 999).sum())

print("\nMonthly income below 1000:")
print((df["monthly_income"] < 1000).sum())

print("\nMonthly income = 9999999:")
print((df["monthly_income"] == 9999999).sum())

Age = 0:
17

Employment years = 999:
339

Monthly income below 1000:
80

Monthly income = 9999999:
1

In [14]:
print("Monthly income = 9999999:")
print((df["monthly_income"] == 9999999).sum())

Monthly income = 9999999:
1

In [15]:
print("Missing account_closed_date:")
print(df["account_closed_date"].isna().sum())

print("\nPercentage missing:")
print(df["account_closed_date"].isna().mean() * 100)

Missing account_closed_date:
4413

Percentage missing:
82.48598130841121

In [16]:
missing_count = df.isna().sum()

missing_percent = (missing_count / len(df)) * 100

missing_table = pd.DataFrame({
    "Missing Count": missing_count,
    "Missing %": missing_percent
})

missing_table.sort_values("Missing %", ascending=False)

                     Missing Count  Missing %
account_closed_date           4413  82.485981
monthly_income                 755  14.112150
age                              0   0.000000
loan_id                          0   0.000000
employment_type                  0   0.000000
employment_years                 0   0.000000
loan_amount                      0   0.000000
applicant_name                   0   0.000000
loan_date                        0   0.000000
credit_score                     0   0.000000
collection_calls                 0   0.000000
region                           0   0.000000
recovery_amount                  0   0.000000
risk_flag                        0   0.000000
late_but_repaid                  0   0.000000
defaulted_12m                    0   0.000000

In [17]:
print("Possible placeholder values:")

for col in df.columns:
    if df[col].dtype == "object":
        print("\n", col)
        print(df[col].value_counts(dropna=False).head(20))

Possible placeholder values:

 applicant_name
applicant_name
Vijay Gohil        27
Pooja Bhatt        27
Sanjay Bhatt       27
Rekha Gohil        27
Nirav Rathod       27
Jignesh Zala       26
Dhruv Mehta        26
Harsh Shah         25
Bhavesh Solanki    25
Vijay Chauhan      24
Meera Jadeja       24
Amit Vora          24
Kiran Rathod       24
Meera Gohil        24
Amit Jadeja        24
Sanjay Zala        24
Jignesh Parmar     24
Mahesh Zala        24
Pooja Gohil        23
Kiran Jadeja       23
Name: count, dtype: int64

 employment_type
employment_type
Salaried         2117
Business         1073
Daily wage        838
Self-employed     836
Self employed     140
Self-Employed     124
SE                117
self employed     105
Name: count, dtype: int64

 loan_date
loan_date
2021-09-24    14
2022-07-21    14
2022-07-23    14
2021-11-03    13
2021-09-28    13
2021-05-05    13
2022-08-31    13
2022-05-17    12
2022-02-04    12
2022-08-28    12
2022-02-26    12
2022-09-30    12
2021-04-03    12
2022-06-21    12
2021-03-04    12
2021-07-27    12
2022-01-16    12
2023-02-10    12
2022-08-29    12
2022-04-25    12
Name: count, dtype: int64

 region
region
Saurashtra         1637
North Gujarat      1069
Central Gujarat    1037
Kutch               820
South Gujarat       787
Name: count, dtype: int64

 account_closed_date
account_closed_date
NaN           4413
2023-09-12       6
2023-06-13       6
2022-03-29       6
2022-10-10       6
2022-03-08       5
2023-11-03       5
2023-12-13       4
2023-04-16       4
2022-04-04       4
2023-03-24       4
2022-04-02       4
2022-12-24       4
2023-03-29       4
2023-05-09       4
2024-02-13       4
2023-08-18       4
2022-10-03       4
2023-03-10       4
2022-02-03       4
Name: count, dtype: int64

 risk_flag
risk_flag
low     4181
high    1169
Name: count, dtype: int64

 late_but_repaid
late_but_repaid
N    5016
Y     334
Name: count, dtype: int64

In [18]:
print("Missing monthly income:")
print(df["monthly_income"].isna().sum())

print("\nMissing percentage:")
print(df["monthly_income"].isna().mean() * 100)

Missing monthly income:
755

Missing percentage:
14.11214953271028

In [19]:
income_missing = df["monthly_income"].isna()

default_rate_comparison = df.groupby(income_missing)["defaulted_12m"].mean()

print(default_rate_comparison)

monthly_income
False    0.163221
True     0.560265
Name: defaulted_12m, dtype: float64

In [20]:
print("Default rate when income is MISSING:")
print(df.loc[df["monthly_income"].isna(), "defaulted_12m"].mean())

print("\nDefault rate when income is PRESENT:")
print(df.loc[df["monthly_income"].notna(), "defaulted_12m"].mean())

Default rate when income is MISSING:
0.5602649006622517

Default rate when income is PRESENT:
0.1632208922742111

In [21]:
# Show all columns
for col in df.columns:
    print(col)

loan_id
applicant_name
age
employment_type
employment_years
monthly_income
loan_amount
loan_date
credit_score
region
collection_calls
recovery_amount
account_closed_date
risk_flag
late_but_repaid
defaulted_12m

In [22]:
leakage_check = pd.DataFrame({
    "Feature": [
        "loan_id",
        "applicant_name",
        "age",
        "employment_type",
        "employment_years",
        "monthly_income",
        "loan_amount",
        "loan_date",
        "credit_score",
        "region",
        "collection_calls",
        "recovery_amount",
        "account_closed_date",
        "risk_flag",
        "late_but_repaid"
    ]
})

leakage_check

                Feature
0               loan_id
1        applicant_name
2                   age
3       employment_type
4      employment_years
5        monthly_income
6           loan_amount
7             loan_date
8          credit_score
9                region
10     collection_calls
11      recovery_amount
12  account_closed_date
13            risk_flag
14      late_but_repaid

In [23]:
suspicious_features = [
    "collection_calls",
    "recovery_amount",
    "account_closed_date",
    "late_but_repaid",
    "risk_flag"
]

df[suspicious_features].head()

,collection_calls,recovery_amount,account_closed_date,late_but_repaid,risk_flag
0,0,0,2023-04-27,N,low
1,2,0,2023-01-09,N,low
2,0,0,NaN,N,low
3,0,0,NaN,N,low
4,0,0,NaN,Y,high

In [24]:
X = df.drop(columns=["defaulted_12m"])
y = df["defaulted_12m"]

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (5350, 15)
y shape: (5350,)

In [28]:
X = X.drop(columns=["loan_id", "applicant_name"], errors="ignore")

print(X.columns.tolist())

['age', 'employment_type', 'employment_years', 'monthly_income', 'loan_amount', 'loan_date', 'credit_score', 'region', 'collection_calls', 'recovery_amount', 'account_closed_date', 'risk_flag', 'late_but_repaid']

In [29]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder

numeric_features = X.select_dtypes(include=["int64", "float64"]).columns.tolist()
categorical_features = X.select_dtypes(include=["object"]).columns.tolist()

print("Numeric features:")
print(numeric_features)

print("\nCategorical features:")
print(categorical_features)

Numeric features:
['age', 'employment_years', 'monthly_income', 'loan_amount', 'credit_score', 'collection_calls', 'recovery_amount']

Categorical features:
['employment_type', 'loan_date', 'region', 'account_closed_date', 'risk_flag', 'late_but_repaid']

In [30]:
numeric_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median"))
])

categorical_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore"))
])

preprocessor = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, numeric_features),
        ("cat", categorical_transformer, categorical_features)
    ]
)

In [31]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import StratifiedKFold, cross_val_score

model = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("classifier", GradientBoostingClassifier(random_state=42))
])

cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

scores = cross_val_score(
    model,
    X,
    y,
    cv=cv,
    scoring="roc_auc"
)

print("AUC scores for 5 folds:")
print(scores)

print("\nMean 5-fold AUC:")
print(scores.mean())

AUC scores for 5 folds:
[0.92603924 0.94917801 0.91682507 0.94448465 0.9363919 ]

Mean 5-fold AUC:
0.9345837743094485

In [32]:
leaky_features = [
    "collection_calls",
    "recovery_amount",
    "account_closed_date",
    "late_but_repaid"
]

X_no_leak = df.drop(
    columns=["defaulted_12m", "loan_id", "applicant_name"] + leaky_features
)

print("Remaining features:")
print(X_no_leak.columns.tolist())

Remaining features:
['age', 'employment_type', 'employment_years', 'monthly_income', 'loan_amount', 'loan_date', 'credit_score', 'region', 'risk_flag']

In [33]:
numeric_features_no_leak = X_no_leak.select_dtypes(
    include=["int64", "float64"]
).columns.tolist()

categorical_features_no_leak = X_no_leak.select_dtypes(
    include=["object"]
).columns.tolist()

print("Numeric:")
print(numeric_features_no_leak)

print("\nCategorical:")
print(categorical_features_no_leak)

Numeric:
['age', 'employment_years', 'monthly_income', 'loan_amount', 'credit_score']

Categorical:
['employment_type', 'loan_date', 'region', 'risk_flag']

In [34]:
numeric_transformer_no_leak = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median"))
])

categorical_transformer_no_leak = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore"))
])

preprocessor_no_leak = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer_no_leak, numeric_features_no_leak),
        ("cat", categorical_transformer_no_leak, categorical_features_no_leak)
    ]
)

In [35]:
model_no_leak = Pipeline(steps=[
    ("preprocessor", preprocessor_no_leak),
    ("classifier", GradientBoostingClassifier(random_state=42))
])

scores_no_leak = cross_val_score(
    model_no_leak,
    X_no_leak,
    y,
    cv=cv,
    scoring="roc_auc"
)

print("AUC scores after removing leakage:")
print(scores_no_leak)

print("\nMean 5-fold AUC after removing leakage:")
print(scores_no_leak.mean())

AUC scores after removing leakage:
[0.8484414  0.8525411  0.84148809 0.85407058 0.84470378]

Mean 5-fold AUC after removing leakage:
0.8482489901701802

In [36]:
leakage_features = [
    "collection_calls",
    "recovery_amount",
    "account_closed_date",
    "late_but_repaid",
    "risk_flag"
]

leakage_results = []

for feature in leakage_features:

    X_test = df.drop(
        columns=["defaulted_12m", "loan_id", "applicant_name", feature]
    )

    numeric_features_test = X_test.select_dtypes(
        include=["int64", "float64"]
    ).columns.tolist()

    categorical_features_test = X_test.select_dtypes(
        include=["object"]
    ).columns.tolist()

    preprocessor_test = ColumnTransformer(
        transformers=[
            (
                "num",
                Pipeline([
                    ("imputer", SimpleImputer(strategy="median"))
                ]),
                numeric_features_test
            ),
            (
                "cat",
                Pipeline([
                    ("imputer", SimpleImputer(strategy="most_frequent")),
                    ("onehot", OneHotEncoder(handle_unknown="ignore"))
                ]),
                categorical_features_test
            )
        ]
    )

    model_test = Pipeline([
        ("preprocessor", preprocessor_test),
        ("classifier", GradientBoostingClassifier(random_state=42))
    ])

    scores_test = cross_val_score(
        model_test,
        X_test,
        y,
        cv=cv,
        scoring="roc_auc"
    )

    leakage_results.append({
        "Feature Removed": feature,
        "Mean 5-Fold AUC": scores_test.mean()
    })

leakage_table = pd.DataFrame(leakage_results)

leakage_table

       Feature Removed  Mean 5-Fold AUC
0     collection_calls         0.932004
1      recovery_amount         0.931288
2  account_closed_date         0.934657
3      late_but_repaid         0.909244
4            risk_flag         0.933695

In [37]:
baseline_auc = scores.mean()

leakage_report = pd.DataFrame({
    "Feature": [
        "collection_calls",
        "recovery_amount",
        "account_closed_date",
        "late_but_repaid",
        "risk_flag"
    ],
    "AUC Before Removal": [
        baseline_auc,
        baseline_auc,
        baseline_auc,
        baseline_auc,
        baseline_auc
    ],
    "AUC After Removal": [
        0.932004,
        0.931288,
        0.934657,
        0.909244,
        0.933695
    ]
})

leakage_report["AUC Change"] = (
    leakage_report["AUC After Removal"]
    - leakage_report["AUC Before Removal"]
)

leakage_report

               Feature  AUC Before Removal  AUC After Removal  AUC Change
0     collection_calls            0.934584           0.932004   -0.002580
1      recovery_amount            0.934584           0.931288   -0.003296
2  account_closed_date            0.934584           0.934657    0.000073
3      late_but_repaid            0.934584           0.909244   -0.025340
4            risk_flag            0.934584           0.933695   -0.000889

In [38]:
print(leakage_report.to_string(index=False))

            Feature  AUC Before Removal  AUC After Removal  AUC Change
   collection_calls            0.934584           0.932004   -0.002580
    recovery_amount            0.934584           0.931288   -0.003296
account_closed_date            0.934584           0.934657    0.000073
    late_but_repaid            0.934584           0.909244   -0.025340
          risk_flag            0.934584           0.933695   -0.000889

In [40]:
# Count exact duplicate rows

exact_duplicates = df.duplicated().sum()

print("Exact duplicate rows:", exact_duplicates)

Exact duplicate rows: 200

In [41]:
# Show exact duplicate rows

duplicates = df[df.duplicated(keep=False)]

print("Total rows involved in exact duplicates:", len(duplicates))

duplicates.head(20)

Total rows involved in exact duplicates: 400

,loan_id,applicant_name,age,employment_type,employment_years,monthly_income,loan_amount,loan_date,credit_score,region,collection_calls,recovery_amount,account_closed_date,risk_flag,late_but_repaid,defaulted_12m
26,12616,Ravi Rathod,43,Salaried,20,51300.0,407000,2022-11-12,679,Central Gujarat,0,0,NaN,low,N,1
27,10208,Bhavesh Vora,31,Business,3,57000.0,993000,2021-10-19,742,Saurashtra,0,0,NaN,low,N,0
42,11354,Rekha Vora,49,Salaried,21,33100.0,287000,2023-03-01,615,South Gujarat,0,0,NaN,high,N,0
44,14822,Bhavesh Patel,35,Salaried,7,26400.0,104000,2021-02-10,676,South Gujarat,9,57800,2021-12-06,high,N,1
55,13102,Nisha Vora,43,Daily wage,21,18200.0,287000,2023-04-23,626,Central Gujarat,0,0,NaN,low,N,0
57,14357,Ravi Bhatt,21,Salaried,0,36600.0,323000,2022-09-28,774,Kutch,7,106800,2023-04-19,low,N,1
63,13226,Harsh Shah,41,Daily wage,15,12100.0,104000,2022-07-23,726,Central Gujarat,0,0,NaN,low,N,0
87,10171,Kiran Jadeja,21,Self-employed,0,36600.0,201000,2022-09-20,598,Saurashtra,0,0,NaN,low,N,0
100,11661,Nisha Dave,30,Salaried,9,17900.0,147000,2022-08-23,782,South Gujarat,0,0,NaN,low,Y,0
119,14132,Pooja Patel,21,Salaried,0,31800.0,312000,2021-07-18,629,Saurashtra,0,0,NaN,low,N,0
144,11985,Mahesh Jadeja,39,Salaried,999,39300.0,596000,2022-10-14,732,South Gujarat,0,0,NaN,low,N,0
195,11632,Rekha Mehta,42,Self employed,15,37400.0,530000,2023-06-13,761,North Gujarat,0,0,NaN,low,N,0
220,13538,Priya Vora,31,Salaried,9,42700.0,768000,2021-07-25,687,Saurashtra,0,0,NaN,low,N,0
229,14860,Priya Joshi,47,Business,26,NaN,729000,2023-03-27,694,Central Gujarat,3,289300,2023-12-13,high,N,1
258,12825,Harsh Trivedi,48,Self-employed,27,48300.0,372000,2021-09-09,678,North Gujarat,0,0,NaN,low,N,0
280,10413,Harsh Chauhan,39,Salaried,11,54700.0,780000,2022-04-10,692,Central Gujarat,0,0,NaN,low,N,0
302,14551,Harsh Trivedi,37,Self employed,11,NaN,615000,2022-09-02,626,Central Gujarat,8,226900,2023-09-12,high,N,1
304,14391,Rekha Solanki,52,Salaried,30,24100.0,293000,2023-05-31,647,Kutch,0,0,NaN,low,N,0
305,14352,Ravi Patel,45,Daily wage,999,16900.0,92000,2023-01-29,645,Central Gujarat,1,0,NaN,low,N,0
328,11228,Bhavesh Dave,54,Salaried,30,21500.0,241000,2021-07-19,644,South Gujarat,0,0,NaN,low,Y,0

In [42]:
# Create a copy with exact duplicate rows removed

df_no_duplicates = df.drop_duplicates().copy()

print("Original shape:", df.shape)
print("After removing duplicates:", df_no_duplicates.shape)
print("Rows removed:", len(df) - len(df_no_duplicates))

Original shape: (5350, 16)
After removing duplicates: (5150, 16)
Rows removed: 200

In [43]:
df.duplicated(keep=False)

0       False
1       False
2       False
3       False
4       False
        ...
5345    False
5346    False
5347    False
5348    False
5349    False
Length: 5350, dtype: bool

In [44]:
df.drop_duplicates()

,loan_id,applicant_name,age,employment_type,employment_years,monthly_income,loan_amount,loan_date,credit_score,region,collection_calls,recovery_amount,account_closed_date,risk_flag,late_but_repaid,defaulted_12m
0,10136,Sanjay Patel,46,Salaried,20,39500.0,283000,2022-08-27,676,Saurashtra,0,0,2023-04-27,low,N,0
1,10825,Kinjal Solanki,47,SE,22,25200.0,457000,2022-05-07,567,Saurashtra,2,0,2023-01-09,low,N,0
2,11557,Priya Zala,52,Daily wage,31,9800.0,52000,2022-04-22,684,North Gujarat,0,0,NaN,low,N,1
3,10867,Kiran Vora,46,self employed,18,NaN,340000,2022-10-09,707,Saurashtra,0,0,NaN,low,N,0
4,10431,Dhruv Dave,27,Salaried,2,NaN,442000,2023-05-23,728,Saurashtra,0,0,NaN,high,Y,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5345,10711,Anita Jadeja,55,Self employed,31,NaN,565000,2023-03-11,699,Saurashtra,0,0,NaN,low,N,0
5346,14055,Dipti Trivedi,37,Business,10,35400.0,543000,2022-05-29,595,South Gujarat,5,92500,2022-12-22,high,N,1
5347,15049,kiran shah,33,Business,11,22000.0,257000,2021-11-15,775,Saurashtra,0,0,NaN,low,N,0
5348,11337,Mahesh Joshi,48,Salaried,23,39000.0,338000,2022-03-14,783,North Gujarat,0,0,NaN,low,Y,0
5349,14184,Amit Vora,46,Business,19,79500.0,806000,2022-10-10,636,South Gujarat,1,0,NaN,low,Y,0